name: Docker Builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Build and test
        run: docker build .
